<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>NotGodlike.TitanfallMovement</AssemblyName>
    <Version>1.8.7</Version>
    <Authors>NotGodlike</Authors>
    <AssemblyTitle>Titanfall Movement</AssemblyTitle>
    <Description>Titanfall 2 inspired momentum, slides, double jumps, crouching and wall running for H3VR.</Description>
    <PackageProjectUrl></PackageProjectUrl>
    <TargetFramework>net35</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <Optimize>true</Optimize>
    <DebugType>portable</DebugType>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <RestoreAdditionalProjectSources>https://api.nuget.org/v3/index.json</RestoreAdditionalProjectSources>
    <H3VRPath Condition="'$(H3VRPath)' == ''">H:\SteamLibrary\steamapps\common\H3VR</H3VRPath>
    <BepInExPath Condition="'$(BepInExPath)' == ''">E:\Games\r2mods\H3VR\profiles\Default\BepInEx</BepInExPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <Optimize>false</Optimize>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net35" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(H3VRPath)\h3vr_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(H3VRPath)\h3vr_Data\Managed\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(BepInExPath)\core\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(BepInExPath)\core\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\jump sounds\*.wav">
      <Link>jump sounds\%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Target Name="PackageThunderstore" AfterTargets="Build" Condition="'$(OS)' == 'Windows_NT'">
    <Exec Command="powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File &quot;$(MSBuildProjectDirectory)\..\tools\make_ts.ps1&quot; -ProjectFilePath &quot;$(MSBuildProjectFullPath)&quot; -TargetPath &quot;$(TargetPath)&quot;" />
  </Target>
</Project>
